### ISSUE TITLE
Unify IPA/KZG interfaces

### ISSUE THREAD

**Issue by codygunton** [AztecProtocol/barretenberg#166] opened 2023-02-17 19:13 UTC
From https://github.com/AztecProtocol/barretenberg/pull/31#pullrequestreview-1240637105: methods should be added that batch prove and batch verify multiple polynomial commitments.

**Comment by adr1anh** [comment] 2023-04-12 09:18
For now, we don't need batching since that can be handled by the prover as a previous step. (In a similar way batching is handled by Gemini). 

If we want to use IPA as a drop in replacement for KZG, then we only need to open a single polynomial since Shplonk handles batching.

However, it would be good to accept the OpeningClaim type as input to unify the interface with KZG.

**Comment by maramihali** [comment] 2023-05-03 14:29
duplicate of #236

**Comment by maramihali** [comment] 2023-06-01 11:27
closed by #445

**Closed as completed** 2023-06-01 11:28 UTC
