### ISSUE TITLE
Create constraints for hashing in Ultra

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#1042] opened 2024-06-28 14:56 UTC
Constraints are currently not added when hashing in an Ultra arithmetized circuit (i.e. a recursive verifier). This was done for convenience since Ultra does not have poseidon.

**Comment by lucasxia01** [comment] 2024-09-23 18:19
Duplicate of https://github.com/AztecProtocol/barretenberg/issues/852.

**Closed as completed by lucasxia01** 2024-09-23 18:19 UTC
